In [1]:
import pandas as pd

In [2]:
census_data=pd.read_csv("../VIC/2021Census_G01_VIC_POA.csv")
census_data.head()

,POA_CODE_2021,Tot_P_M,Tot_P_F,Tot_P_P,Age_0_4_yr_M,Age_0_4_yr_F,Age_0_4_yr_P,Age_5_14_yr_M,Age_5_14_yr_F,Age_5_14_yr_P,...,High_yr_schl_comp_Yr_8_belw_P,High_yr_schl_comp_D_n_g_sch_M,High_yr_schl_comp_D_n_g_sch_F,High_yr_schl_comp_D_n_g_sch_P,Count_psns_occ_priv_dwgs_M,Count_psns_occ_priv_dwgs_F,Count_psns_occ_priv_dwgs_P,Count_Persons_other_dwgs_M,Count_Persons_other_dwgs_F,Count_Persons_other_dwgs_P
0,POA3000,21548,21539,43084,347,345,697,388,376,767,...,287,155,171,322,18338,18650,36985,4327,3590,7916
1,POA3002,2353,2545,4896,59,53,110,87,91,176,...,49,6,4,9,2060,2235,4297,538,519,1058
2,POA3003,4093,3926,8025,118,137,250,167,167,336,...,71,17,24,38,3650,3651,7304,424,206,630
3,POA3004,5655,5827,11482,168,193,362,224,223,448,...,60,19,21,40,4891,5089,9983,1256,991,2251
4,POA3006,11499,11197,22699,365,332,702,333,326,657,...,108,55,58,110,10679,10386,21065,993,863,1856

In [3]:
census_data["POA_CODE_2021"]=census_data["POA_CODE_2021"].str.replace('POA', '')

In [4]:
census_data

,POA_CODE_2021,Tot_P_M,Tot_P_F,Tot_P_P,Age_0_4_yr_M,Age_0_4_yr_F,Age_0_4_yr_P,Age_5_14_yr_M,Age_5_14_yr_F,Age_5_14_yr_P,...,High_yr_schl_comp_Yr_8_belw_P,High_yr_schl_comp_D_n_g_sch_M,High_yr_schl_comp_D_n_g_sch_F,High_yr_schl_comp_D_n_g_sch_P,Count_psns_occ_priv_dwgs_M,Count_psns_occ_priv_dwgs_F,Count_psns_occ_priv_dwgs_P,Count_Persons_other_dwgs_M,Count_Persons_other_dwgs_F,Count_Persons_other_dwgs_P
0,3000,21548,21539,43084,347,345,697,388,376,767,...,287,155,171,322,18338,18650,36985,4327,3590,7916
1,3002,2353,2545,4896,59,53,110,87,91,176,...,49,6,4,9,2060,2235,4297,538,519,1058
2,3003,4093,3926,8025,118,137,250,167,167,336,...,71,17,24,38,3650,3651,7304,424,206,630
3,3004,5655,5827,11482,168,193,362,224,223,448,...,60,19,21,40,4891,5089,9983,1256,991,2251
4,3006,11499,11197,22699,365,332,702,333,326,657,...,108,55,58,110,10679,10386,21065,993,863,1856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689,3990,55,62,118,0,3,6,4,4,6,...,3,0,0,0,57,59,111,3,7,6
690,3991,204,205,405,10,11,21,20,25,39,...,25,4,0,4,173,177,348,20,22,43
691,3992,650,631,1281,37,29,67,84,76,157,...,43,4,4,10,597,589,1186,38,39,77
692,3995,5588,6009,11596,238,244,489,623,576,1200,...,627,34,33,66,5153,5513,10668,370,442,812
693,3996,3194,3453,6649,150,162,310,371,351,726,...,224,18,20,40,2886,3164,6047,259,240,501